spring:
  application:
    name: CapstoneDesign

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/capstone_design?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: false
    show-sql: false
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"

auth:
  jwt:
    issuer: "HoseoCapstoneDesign"
    access-key: "GxNfK0XvN7pM3jB2YqRtZl4s8dF1vC9qTzE5aWm2sUuLxOeH"
    refresh-key: "JrW4pD7aZsQ8xR1mTgB2yV5fNnL9kC3vEoH6qUuP0wYtSxMz"
    access-ttl: 15 #min
    refresh-ttl: 7 # days
    cookie-name: "REFRESH_TOKEN"
    cookie-http-only: true
    cookie-secure: false    # https면 true
    cookie-samesite: "Lax"
    front-redirect-url: "http://localhost:5500/index.html"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-handlers-package: com.jam.socialNetworkService.global.handler
  type-aliases-package: com.example.domain
  configuration:
    map-underscore-to-camel-case: true
