spring:
  application:
    name: CapstoneDesign

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/capstone_design?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true  #prod -> os var
    username: root  #prod -> os var
    password: root  #prod -> os var

  jpa:
    hibernate:
      ddl-auto: create  #prod -> update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: false
    show-sql: false
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"  #prod -> os var

  cloud:
    aws:
      sqs:
        queue-not-found-strategy: FAIL
      region:
        static: ${SQS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

app:
  frontend:
    baseUrl: ${FRONTEND_BASE_URL}
  aws:
    sqs:
      analysis-queue: ${SQS_ANALYSIS_QUEUE}
      dlq-queue: ${SQS_DLQ}
      notification-queue: ${SQS_NOTIFICATION_QUEUE}

auth:
  jwt:
    issuer: "HoseoCapstoneDesign"  #prod -> os var
    access-key: "GxNfK0XvN7pM3jB2YqRtZl4s8dF1vC9qTzE5aWm2sUuLxOeH"  #prod -> os var
    refresh-key: "JrW4pD7aZsQ8xR1mTgB2yV5fNnL9kC3vEoH6qUuP0wYtSxMz"  #prod -> os var
    access-ttl: 15 #min
    refresh-ttl: 7 # days
    cookie-name: "REFRESH_TOKEN"  #prod -> os var
    cookie-http-only: true
    cookie-secure: false    # https면 true
    cookie-samesite: "Lax"
    front-redirect-url: "http://localhost:8080/tmp/oauth2/test"  #prod -> os var

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-handlers-package: com.jam.socialNetworkService.global.handler
  type-aliases-package: com.example.domain
  configuration:
    map-underscore-to-camel-case: true

github:
  app:
    app-id: ${GITHUB_APP_ID}
    private-key: ${GITHUB_APP_PRIVATE_KEY}
    state-secret: ${GITHUB_APP_STATE_SECRET}
  webhook:
    secret: ${GITHUB_WEBHOOK_SECRET}