global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: capstone-spring
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          application: capstone-main
          env: local

  - job_name: git-worker
    metrics_path: /metrics
    static_configs:
      - targets:
          - 172.19.228.23:3000
        labels:
          application: git-worker
          env: local
